import type { ScanResult } from "../../src/scan.js";

/**
 * A sample Scan result used only by the Vite dev server, where no `cerebro
 * build` injection has happened. Exercises every display state: deprecation,
 * untyped and unanalyzed props, all three footguns, broken connections,
 * activity logs, dependency edges, and a dirty-tree warning.
 */
export const DEV_SCAN: ScanResult = {
  schemaVersion: 1,
  toolVersion: "0.0.0-dev",
  scannedCommit: "f3a9c1d2e8b7a6f5c4d3b2a1f0e9d8c7b6a5f4e3",
  committedAt: "2026-06-09T14:32:00-04:00",
  config: {
    componentsPath: "src/components",
    usesStorybook: true,
    usesFigmaCodeConnect: true,
    tracksActivityLog: true,
    activityLogDepth: 20,
  },
  components: [
    {
      name: "Avatar",
      path: "src/components/Avatar/Avatar.tsx",
      tests: { total: 12, skipped: 0, only: 0 },
      stories: { total: 3, csf1: 0, csf2: 0, csf3: 3, other: 0 },
      figmaConnections: [{ url: "https://www.figma.com/design/abc/ds?node-id=101-2" }],
      deprecated: false,
      exportShape: "named-reexport",
      propsTyping: "typed",
      definitionKind: "function",
      memoWithChildren: false,
      nestedComponentDefinition: false,
      forwardRefWithoutRef: false,
      activityLog: [
        {
          sha: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0",
          committedAt: "2026-06-08T11:20:00-04:00",
          authorName: "Steve Bourgoin",
          authorEmail: "steve@example.com",
          subject: "feat(avatar): support fallback initials",
        },
        {
          sha: "b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1",
          committedAt: "2026-05-28T09:05:00-04:00",
          authorName: "Maya Chen",
          authorEmail: "maya@example.com",
          subject: "fix(avatar): clamp image aspect ratio",
        },
      ],
      dependsOn: [],
      externalDependencies: ["clsx"],
    },
    {
      name: "Button",
      path: "src/components/Button/Button.tsx",
      tests: { total: 24, skipped: 2, only: 0 },
      stories: { total: 6, csf1: 0, csf2: 2, csf3: 4, other: 0 },
      figmaConnections: [
        { url: "https://www.figma.com/design/abc/ds?node-id=1-2" },
        { url: null, variant: { variant: "ghost" } },
      ],
      deprecated: false,
      exportShape: "named-reexport",
      propsTyping: "typed",
      definitionKind: "function",
      memoWithChildren: false,
      nestedComponentDefinition: false,
      forwardRefWithoutRef: false,
      activityLog: [
        {
          sha: "c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2",
          committedAt: "2026-06-05T16:48:00-04:00",
          authorName: "Steve Bourgoin",
          authorEmail: "steve@example.com",
          subject: "refactor(button): extract size tokens",
        },
      ],
      dependsOn: ["Spinner"],
      externalDependencies: ["clsx"],
    },
    {
      name: "Card",
      path: "src/components/Card/Card.tsx",
      tests: { total: 4, skipped: 0, only: 1 },
      stories: { total: 2, csf1: 1, csf2: 0, csf3: 1, other: 0 },
      figmaConnections: [],
      deprecated: false,
      exportShape: "default-reexport",
      propsTyping: "untyped",
      definitionKind: "function",
      memoWithChildren: true,
      nestedComponentDefinition: false,
      forwardRefWithoutRef: false,
      activityLog: [
        {
          sha: "d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3",
          committedAt: "2025-11-14T10:00:00-05:00",
          authorName: "Maya Chen",
          authorEmail: "maya@example.com",
          subject: "chore(card): move styles inline",
        },
      ],
      dependsOn: ["Avatar", "Button"],
      externalDependencies: ["clsx", "lodash"],
    },
    {
      name: "LegacyTable",
      path: "src/components/LegacyTable/LegacyTable.tsx",
      tests: { total: 0, skipped: 0, only: 0 },
      stories: { total: 0, csf1: 0, csf2: 0, csf3: 0, other: 0 },
      figmaConnections: [],
      deprecated: true,
      exportShape: "renamed-reexport",
      propsTyping: "unanalyzed",
      definitionKind: "class",
      memoWithChildren: false,
      nestedComponentDefinition: true,
      forwardRefWithoutRef: false,
      activityLog: [
        {
          sha: "e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4",
          committedAt: "2024-03-02T13:30:00-05:00",
          authorName: "Old Maintainer",
          authorEmail: "old@example.com",
          subject: "fix(table): IE11 scroll shim",
        },
      ],
      dependsOn: [],
      externalDependencies: ["lodash", "moment"],
    },
    {
      name: "Spinner",
      path: "src/components/Spinner/Spinner.tsx",
      tests: { total: 6, skipped: 0, only: 0 },
      stories: { total: 1, csf1: 0, csf2: 0, csf3: 1, other: 0 },
      figmaConnections: [{ url: "https://www.figma.com/design/abc/ds?node-id=42-1" }],
      deprecated: false,
      exportShape: "named-reexport",
      propsTyping: "typed",
      definitionKind: "function",
      memoWithChildren: false,
      nestedComponentDefinition: false,
      forwardRefWithoutRef: true,
      activityLog: [
        {
          sha: "f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5",
          committedAt: "2026-04-19T08:12:00-04:00",
          authorName: "Steve Bourgoin",
          authorEmail: "steve@example.com",
          subject: "perf(spinner): css-only animation",
        },
      ],
      dependsOn: [],
      externalDependencies: [],
    },
    {
      name: "Tooltip",
      path: "src/components/Tooltip/Tooltip.tsx",
      tests: { total: 9, skipped: 1, only: 0 },
      stories: { total: 4, csf1: 0, csf2: 1, csf3: 3, other: 0 },
      figmaConnections: [{ url: null }],
      deprecated: false,
      exportShape: "barrel-local",
      propsTyping: "typed",
      definitionKind: "function",
      memoWithChildren: false,
      nestedComponentDefinition: false,
      forwardRefWithoutRef: false,
      activityLog: [
        {
          sha: "a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6",
          committedAt: "2026-06-01T17:45:00-04:00",
          authorName: "Maya Chen",
          authorEmail: "maya@example.com",
          subject: "feat(tooltip): placement collision handling",
        },
      ],
      dependsOn: ["Card"],
      externalDependencies: ["@floating-ui/react"],
    },
  ],
  warnings: ["Working tree is dirty: the scan reflects uncommitted changes."],
  git: { available: true, shallow: false },
};
